import Head from "next/head";
// import Image from "next/image";
import styles from "@/styles/Home.module.css";
import React, { useEffect, useState, createContext, useContext } from "react";
import Header from "../components/Header";
import UploadToIPFS from "../components/UploadToIPFS";
import ShowBalance from "../components/ShowBalance";
import ShowNFT from "../components/ShowNFT";

export default function Home() {
  return (
    <>
      <Head>
        <title>Document Verification</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>
        <ShowBalance />
        <UploadToIPFS />
      </div>
      <div style={{ marginTop: "100px" }}>
        <ShowNFT />
      </div>
      <main className={styles.main}>
        <div className={styles.description}>
        </div>

        <div className={styles.grid}></div>
      </main>
    </>
  );
}
